# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'https://ruby.taobao.org'

gem "middleman", "~>3.2.2"
gem "middleman-core"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

gem 'middleman-bower', github: 'bbtfr/middleman-bower'

gem "rack-reverse-proxy"

group :development do
	# Live-reloading plugin
  gem "middleman-livereload", "~> 3.1.0"
	gem 'middleman-deploy'

end

	